In [3]:
l = [2323,232,4343,-23,53, 324]

In [4]:
l

[2323, 232, 4343, -23, 53, 324]

In [5]:
import numpy as np

In [7]:
a = np.array(l)

In [8]:
a

array([2323,  232, 4343,  -23,   53,  324])

In [9]:
b = np.array([12, 3443, True, 'abc'])

In [10]:
b

array(['12', '3443', 'True', 'abc'], dtype='<U11')

In [11]:
print(b)

['12' '3443' 'True' 'abc']


In [12]:
l.pop()

324

In [13]:
a.mean()

1208.6666666666667

In [14]:
l[::2]

[2323, 4343, 53]

In [15]:
l[2:]

[4343, -23, 53]

In [16]:
#-----------------------------

In [17]:
a

array([2323,  232, 4343,  -23,   53,  324])

In [18]:
a[2:]

array([4343,  -23,   53,  324])

In [19]:
a[2:4]

array([4343,  -23])

In [20]:
c = a.copy()

In [21]:
c

array([2323,  232, 4343,  -23,   53,  324])

In [22]:
c[0] = 0

In [23]:
c

array([   0,  232, 4343,  -23,   53,  324])

In [24]:
a

array([2323,  232, 4343,  -23,   53,  324])